name: ThreadWriter Tauri Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to build and release (e.g. v1.2.0)
        required: false
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        # Für Multi-OS Builds optional erweitern: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libssl-dev \
            librsvg2-dev \
            patchelf \
            build-essential

      - name: Install root deps
        run: npm ci

      - name: Install threadwriter deps
        run: |
          cd threadwriter
          npm ci

      - name: Build and release with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: threadwriter
          tagName: ${{ inputs.tag || github.ref_name }}
          releaseName: ${{ inputs.tag || github.ref_name }}
          releaseBody: |
            ThreadWriter Desktop build for ${{ matrix.platform }}.

            Siehe CHANGELOG für Details.
          releaseDraft: true
          prerelease: false

